name       : svt-av1
version    : 1.3.0
release    : 2
source     :
    - https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.3.0/SVT-AV1-v1.3.0.tar.bz2 : f85fd13ef16880550e425797bdfdf1b0ba310c21d6b343f74ea79dd2fbb2336e
license    :
    - AOMPL-1.0
    - BSD-2-Clause
component  : multimedia.codecs
summary    : Scalable Video Technology for AV1 (SVT-AV1 Encoder)
description: |
    The Scalable Video Technology for AV1 (SVT-AV1 Encoder) is an AV1-compliant encoder library core.
builddeps  :
    - yasm
setup      : |
    %cmake_ninja \
        -DBUILD_APPS=OFF \
        -DBUILD_DEC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
