name       : svt-av1
version    : 1.4.0
release    : 3
source     :
    - https://gitlab.com/AOMediaCodec/SVT-AV1/-/archive/v1.4.0/SVT-AV1-v1.4.0.tar.bz2 : d236457eb0b839716b3609db2ce6db62c103a1ca0e9e2eed0239e194b72bdcd0
license    :
    - AOMPL-1.0
    - BSD-2-Clause
component  : multimedia.codecs
summary    : Scalable Video Technology for AV1 (SVT-AV1 Encoder)
description: |
    The Scalable Video Technology for AV1 (SVT-AV1 Encoder) is an AV1-compliant encoder library core.
builddeps  :
    - yasm
setup      : |
    %cmake_ninja \
        -DBUILD_APPS=OFF \
        -DBUILD_DEC=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
